name: Statement Cleaning Workflow

on:
  push:
    branches: [main] # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger.

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openai

