name: Statement Cleaning Workflow

on:
  push:
    branches: [main] # Trigger on push to main branch
  workflow_dispatch: # Allows manual trigger.

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openai

      - name: Run Python script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python statement_cleaner.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "6696894+amirrr@users.noreply.github.com"
          git config --global user.name "Cleaner Bot"
          git add -A
          git commit -m "Update output file" -a || echo "No changes to commit"
          git push
