name: Normalize Statements

on: [push]

permissions:
  contents: write

jobs:
  normalize-statements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run normalize_statements.py script
      run: |
        python ./.scripts/normalize_statements.py

    - name: Remove any duplicates caused by normalization
      run: |
        python ./.scripts/remove_duplicates_after_normalization.py

    - name: Final format check
      run: |
        python ./.scripts/format_checker.py

    - name: Final dimension check
      run: |
        python ./.scripts/dimension_checker.py
    
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: normalize statements