name: Translate Statements 

on:
  workflow_dispatch: 
    inputs:
      files:
        description: 'Comma-separated list of files to translate in the raw_statements folder'
        required: true
      elicitation:
        description: 'Elicitation method'
        required: true
        default: 'amazon translate'
      committer:
        description: 'Committer name'
        required: true
        default: 'Dan'

jobs:
  translate_statements:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCEScS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
          token: ${{ secrets.PAT }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas boto3

    - name: Run translate_statements_aws script
      run: |
        FILES="${{ github.event.inputs.files }}"
        ELICITATION="${{ github.event.inputs.elicitation }}"
        COMMITTER="${{ github.event.inputs.committer }}"
        IFS=',' read -ra FILE_ARRAY <<< "$FILES"
        for file in "${FILE_ARRAY[@]}"; do
          python translate_statements_aws.py "raw_statements/$file" "$ELICITATION" "$COMMITTER"
        done

    - name: Commit and push translated files
      run: | 
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add raw_statements/*.csv 
        git commit -m "translate statements"
        git push
      if: success()
