name: Translate Statements 

on:
  workflow_dispatch: 
    inputs:
      files:
        description: 'Comma-separated list of files to translate in the raw_statements folder'
        required: true
      elicitation:
        description: 'Elicitation method'
        required: true
        default: 'amazon translate'
      committer:
        description: 'Committer name'
        required: true

permissions:
  contents: write  

jobs:
  translate_statements:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas boto3

    - name: Run translate_statements_aws script
      run: |
        FILES="${{ github.event.inputs.files }}"
        ELICITATION="${{ github.event.inputs.elicitation }}"
        COMMITTER="${{ github.event.inputs.committer }}"
        echo "Files to translate: $FILES"
        python .scripts/translate_statements_aws.py "$FILES" "$ELICITATION" "$COMMITTER"
      
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: translate statements
