name: Translate Statements and Remove Any Duplicates 

on:
  workflow_dispatch: 
    inputs:
      files:
        description: 'Comma-separated list of files to translate in the raw_statements folder'
        required: true
      elicitation:
        description: 'Elicitation method'
        required: true
        default: 'Amazon Translate'
      committer:
        description: 'Committer name'
        required: true

permissions:
  contents: write  

jobs:
  translate_statements:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas boto3

    - name: Run translate_statements_aws.py script
      run: |
        FILES="${{ github.event.inputs.files }}"
        ELICITATION="${{ github.event.inputs.elicitation }}"
        COMMITTER="${{ github.event.inputs.committer }}"
        echo "Files to translate: $FILES"
        python ./.scripts/translate_statements_aws.py "$FILES" "$ELICITATION" "$COMMITTER"

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: translate statements

  check_and_remove_duplicates:
    runs-on: ubuntu-latest
    needs: translate_statements

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Extract duplicate groups (if any)
      run: |
        python ./.scripts/show_groups_of_duplicates.py

    - name: Remove duplicates (if any)
      run: |
        FILES="${{ github.event.inputs.files }}"
        python ./.scripts/remove_duplicates.py "$FILES"

    - name: Final format check
      run: |
        python ./.scripts/format_checker.py

    - name: Final dimension check
      run: |
        python ./.scripts/dimension_checker.py

    - name: Commit and push any changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: remove duplicate statements

  normalize-statements:
    runs-on: ubuntu-latest
    needs: check_and_remove_duplicates

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas 

    - name: Run normalize_statements.py script
      run: |
        python ./.scripts/normalize_statements.py

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: normalize statements
