name: Update Platform Database

on:
  workflow_run:
    workflows: ["Run Dimension Analysis"]
    branches: [main]
    types:
      - completed

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub action IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Setting environment variables
        run: |
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Add GitHub Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 3306 --cidr ${{ steps.ip.outputs.ipv4 }}/32 > /dev/null
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install psycopg2-binary

      #   - name: Run Python script to update RDS database
      #     run: python3 insert_data.py
      #     env:
      #       RDS_HOST: ${{ secrets.RDS_HOST }}
      #       RDS_USER: ${{ secrets.RDS_USER }}
      #       RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      #       DB_NAME: ${{ secrets.DB_NAME }}
      #       DB_TABLE: ${{ secrets.DB_TABLE }}

      - name: Remove GitHub Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 3306 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        if: always()
